<ips:template parameters="$key, $value" />
<div class="ipsField_stackItem_keyValue">
	<span class="i-flex_00 i-align-self_center i-color_soft i-font-weight_500 i-font-size_-1">{lang="storm_devcenter_asset_key"}</span>
	<span data-ipsStack-keyvalue-name="key">{$key|raw}</span>
	<span class="i-flex_00 i-align-self_center i-color_soft i-font-weight_500 i-font-size_-1">{lang="storm_devcenter_asset_value"}</span>
	<span data-ipsStack-keyvalue-name="key">{$value|raw}</span>
</div>