<ips:template parameters="$appKey, $menus, $controller,$start, $active = null, $content=null"/>

<div class="ipsPad ipsClearfix stormColumns">
    <div class="stormColumnLarge">
    <i-tabs class="ipsTabs" id="elTabs_{$controller}_{$appKey}_tabs" data-ipstabbar data-ipstabbar-contentarea="#elTabs_{$controller}_{$appKey}_tabs_content" data-ipstabbar-updateURL="false">
        <div role="tablist">
            {{foreach $menus as $m}}
                <a href='{url="app=storm&module=developer&controller={$controller}&appKey={$appKey}&do={$m}"}' id="elTab_{$controller}_{$appKey}_tab_{$m}" class="ipsTabs__tab" role="tab"{{if $m === $start}} aria-selected="true"{{endif}}>
                    {lang="storm_menu_title_{$m}"}
                </a>
            {{endforeach}}
        </div>
    </i-tabs>
    </div>
    <div class="stormColumnFluid">
        <div id="elTabs_{$controller}_{$appKey}_tabs_content">
        {{if $active !== null}}
        <div id="ipsTabs_elTabs_{$controller}_{$appKey}_tabs_elTab_{$controller}_{$appKey}_tab_{$active}_panel" class="ipsTabs_panel" aria-labelledby="elTab_{$controller}_{$appKey}_tab_{$active}" aria-hidden="false" animating="false">
            {$content|raw}
        </div>
        {{endif}}
    </div>
    </div>
</div>
