<?php
/**
 * @brief		Dev Storm Application Class
 * @author		<a href='https://codingjungle.com'>Michael S. Edwards</a>
 * @copyright	(c) 2025 Michael S. Edwards
 * @package		Invision Community
 * @subpackage	Dev Storm
 * @since		07 Oct 2025
 * @version		
 */
 
namespace IPS\storm;

use IPS\Application as SystemApplication;
use IPS\Helpers\Form\Matrix;
use IPS\Helpers\Form\Select;
use IPS\Helpers\Form\Text;
use IPS\Helpers\Form\TextArea;
use IPS\IPS;
use IPS\Output;

if(\IPS\IN_DEV === true && \IPS\CIC === false && \IPS\CIC2 === false) {
    require \IPS\ROOT_PATH . '/applications/storm/sources/Bootstrap/Bootstrap.php';
}

/**
 * Dev Storm Application Class
 */
class Application extends SystemApplication
{

    public function __construct()
    {
        parent::__construct();
    }

    protected static $loaded = false;
    
    public static function initAutoloader(): void
    {
        if (static::$loaded === false) {
            static::$loaded = true;
            require \IPS\Application::getRootPath('storm') . '/applications/storm/sources/Vendor/autoload.php';
        }
    }

    public function get__icon(): string
    {
        return 'wrench';
    }

//    public function extensionHelper(string $extensionType, string $appKey): array
//    {
//        $return = [];
//        switch( $extensionType )
//        {
//            case 'MetaData':
//                $matrix = new Matrix();
//                $matrix->columns = [
//                    'dtdevplus_lang_key'   => function ($key, $value) {
//                        return new Text($key, $value);
//                    },
//                    'dtdevplus_lang_val'   => function ($key, $value) {
//                        return new TextArea($key, $value);
//                    },
//                    'dtdevplus_lang_no_js' => function ($key, $value) {
//                        $options = [
//                            0 => 'lang.php',
//                            1 => 'jslang.php',
//                            2 => 'lang.php and jslang.php',
//                        ];
//
//                        return new Select($key, $value, false, ['options' => $options]);
//                    },
//                ];
//                break;
//        }
//    }
//
//    public function extensionGenerate(string $extensionType, string $appKey, array $values): array
//    {
//        return parent::extensionGenerate($extensionType, $appKey, $values); // TODO: Change the autogenerated stub
//    }
}