<ips:template parameters="$html" />
<!DOCTYPE html>
<html lang="{expression="\IPS\Member::loggedIn()->language()->bcp47()"}" dir="{{if member.language()->isrtl}}rtl{{else}}ltr{{endif}}">
<head>
    <meta charset="utf-8">
    <title>Diff Export</title>
    <link href="http://netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css" rel="stylesheet">
    <style type="text/css">
        /* ACP */
        html {
            background: #f9f9f9;
            /*background: #f7f7f7;*/
            /*background: #f9f9f9;*/
            min-height: 100%;
            position: relative;
        }

        body {
            font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
            font-size: 13px;
            line-height: 18px;
            color: #404040;
            height: 100%;
        }

        a {
            color: #166693;
            text-decoration: none;
        }

        a:hover {
            color: #cd3816;
        }

        table.diff {
            width: 100%;
        }

        table.diff td, table.diff th {
            width: 50%;
            max-width: 500px;
            overflow-x: auto;
        }

        table.diff td {
            padding: 10px;
            vertical-align: top;
            white-space: pre;
            white-space: pre-wrap;
            font-family: monospace;
        }

        .diffBlank {
            content: '&nbsp;';
        }

        .diffDeleted {
            background:rgb(255,224,224);
        }

        .diffInserted {
            background:rgb(224,255,224);
        }
    </style>
</head>
<body>
{$html|raw}
</div>
</body>
</html>

