<ips:template parameters="\IPS\storm\Profiler\Debug $logs, ?string $class = null" />
<div class="ipsClearfix stormProfilerPadding stormColumns stormProfilerDebugLevel{$logs->level}{{if $class !== null}} {$class}{{endif}}">
    <div class="stormColumnLarge stormProfilerDebugDate stormProfilerListItem">
        <div>
        <div class="stormProfilerDebugTime" title="Date" data-ipsTooltip>
        {$logs->time|raw}
        </div>
        <div class="stormProfilerDebugLevel stormProfilerDebugLevel{$logs->level}" title="Log Level" data-ipsTooltip>
            {$logs->level}
        </div>
        {{if empty($logs->category) === false}}
        <div class="stormCategoryButton" title="Category" data-ipsTooltip>
                {lang="{$logs->category}"}
        </div>
        {{endif}}
        </div>
    </div>
    <div class="stormColumnFluid stormProfilerListItem">
        <div class="ipsClearfix" data-ipstruncate>
            {$logs->log|raw}
        </div>
        <div class="ipsClearfix">
            <button class="float-start ipsButton ipsButton--tiny ipsButton--primary mt-2" type="button" data-open>Backtrace</button>
            <button class="float-end stormCopyButton ipsButton ipsButton--tiny mt-2" type="button"  data-clipboard-text="{$logs->logRaw|raw}">
                <i class="fa fa-copy"></i>
                Copy Message
            </button>
            <button class="float-end stormDeleteButton ipsButton ipsButton--tiny mt-2" type="button" data-delete data-id="{$logs->id}">
                <i class="fa fa-delete-left"></i>
                Delete
            </button>
        </div> 
        <div class="stormProfilerPadding ipsHide"> 
            <div>
                {{foreach $logs->backtrace as $i => $bt}}
                <div class="stormProfilerDebugBt mt-2"> 
                    <a href="{$bt['url']}">
                        {$i}: {$bt['class']}{$bt['type']}{$bt['function']}()<br>
                            {$bt['file']}::{$bt['line']}
                    </a>
                </div>
                {{endforeach}}
            </div>
            <div class="ipsClearfix">
                <button class="stormCopyButton ipsButton ipsButton--tiny mt-2 float-end" type="button" data-clipboard-text="{$logs->btRaw|raw}">
                    <i class="fa fa-copy"></i>
                    Copy Backtrace
                </button>
            </div>
        </div>
    </div>
</div>