<ips:template parameters="string $title, array $data, ?int $last = null" />
<div id="storm_profiler_debug_panel" class="stormDebugPanelParent" data-ipsstormprofilerhide data-ipsstormprofilercopy data-ipsstormprofilerdebug data-last="{$last}">
    <div class="p-10 stormDebugPanel">
        <h2>{$title|raw}</h2>
    </div>
    <div class="stormDebugPanelChild">
        {{foreach $data as $d}}
            {$d|raw}
        {{endforeach}}
    </div>
</div>