<ips:template parameters="$total, $framework, $profiler" />
<div id="storm_execution_panel" class="stormProfilerPanels stormProfilerExecutionPanel ipsHide" data-panels>
    <ul class="ipsList_reset">
        <li>
            Complete: {$total} ms
        </li>
        <li>
            Framework: {$framework} ms
        </li>
        <li>
            Profiler: {$profiler} ms
        </li>
    </ul>
</div>