<ips:template parameters="string $title, bool $search=true, string $class=''" />
<div class="stormProfilerColumns stormProfilerSearch p-10{{if empty($class) === false}} {$class|raw}{{endif}}" data-ipssticky>
    <div class="stormProfilerColumnLarge">
        <h2>{$title|raw}</h2>
    </div>
    {{if $search === true}}
    <div class="stormProfilerColumnFluid stormProfilerWrapper">
        <input type="text" class="ipsInput ipsInput--text" placeholder="Search..." data-search />
        <button data-clear>
            <i class="fa fa-times"></i>
        </button>
        <span></span>
    </div>
    {{endif}}
    <div class="{{if $search === false}}stormProfilerColumnFluid{{else}}stormProfilerSmall{{endif}} ipsClearfix">
        <button type="button" class="ipsButton ipsButton--secondary float-end" data-close>
            <i class="fa fa-close"></i>
        </button>
    </div>
</div>