<ips:template parameters="array $info, array $buttons, array $panels" />
<div id="ElstormProfilerShim" class="stormProfilerShim"></div>
<div id="ElstormProfilerBar" class="stormProfilerBar" data-ipsstormprofiler>
    <div class="stormProfilerBarButtons ipsClearfix">
        {{foreach $buttons['panelButtons'] as $button}}
            {$button|raw}
        {{endforeach}}
    </div>
    <div class="stormColumns">
        <div class="stormColumnHalf">
            <div class="stormProfilerController float-start p-2">
                {$info['loc']|raw}
            </div>
            <div class="stormProfilerSlowestQuery float-start p-2">
                Slowest Query: {$info['sq']|raw}
            </div>
        </div>
        <div class="stormColumnHalf">
            <div class="float-end">
            {{foreach $buttons['extraButtons'] as $button}}
            {$button|raw}
            {{endforeach}}
            </div>
        </div>
    </div>
</div>
<div id="elStormProfilerPanelsContainer" class="stormProfilerPanelsContainer"  data-ipsstormprofilerhide>
    {{foreach $panels as $panel}}
        {$panel|raw}
    {{endforeach}}
</div>