<ips:template parameters="" />

<div class="ipsPadding ipsClearfix" data-ipsdevtoysbase>

    <h4>{lang='devtoys_decoded'}</h4>
    <div class="ipsMargin_top">
        <textarea id="elDecodedContainer">Hello World!!!!!</textarea>
        <div class="ipsClearfix ipsMargin_top">
            <button class="copy ipsPos_right ipsButton ipsButton_primary" data-clear="elDecodedContainer">X {lang='devtoys_clear'}</button>
            <button class="ipsPos_right ipsButton ipsButton_primary ipsMargin_right:half" data-copy="elDecodedContainer">
                <i class="fa fa-copy ipsCursor_pointer"></i>
                {lang='devtoys_copy'}
            </button>
        </div>
    </div>

    <h4>{lang='devtoys_encoded'}</h4>
    <div class="ipsMargin_top">
        <textarea id="elEncodedContainer">SGVsbG8gV29ybGQhISEhIQ==</textarea>
        <div class="ipsClearfix ipsMargin_top">
            <button class="ipsPos_right ipsButton ipsButton_primary" data-clear="elEncodedContainer">X {lang='devtoys_clear'}</button>
            <button class="copy ipsPos_right ipsButton ipsButton_primary ipsMargin_right:half" data-copy="elEncodedContainer">
                <i class="fa fa-copy ipsCursor_pointer"></i>
                {lang='devtoys_copy'}
            </button>
        </div>
    </div>
</div>
