<ips:template parameters="$pos,$bits" />

{{if \IPS\Request::i()->position === null}}
<div class="i-padding-top_0 i-padding_4" data-ipsstormdevtoysbitwise>
    <h4 class="ipsTitle ipsTitle--h4">Position</h4>
    <div class="i-margin-top_2">
        <label>
            <input class="ipsInput ipsInput--text" id="position" name="position" type="number" value="{$pos}" min="1">
        </label>
    </div>
{{endif}}
    <div class="i-padding_1" id="elBitWiseBox">
        <div class="i-flex i-gap_2">
            {{foreach $bits as $bit}}
            {$bit|raw}
            {{endforeach}}
        </div>
    </div>
{{if \IPS\Request::i()->position === null}}
</div>
{{endif}}
