<ips:template parameters="$dates" />

<div class="ipsPadding ipsClearfix" data-ipsdevtoysdates>

    <h4>{lang='devtoys_dates_date'}</h4>
    <div class="ipsMargin_top">
        <label>
            <input id="dates" type="datetime-local" value="{$dates['dates']}" data-input="dates">
        </label>
    </div>

    <h4>{lang='devtoys_dates_unix'}</h4>
    <div class="ipsMargin_top">
        <label>
            <input id="unix" type="number" value="{$dates['unix']}" data-input="unix">
        </label>
    </div>

    <h4>{lang='devtoys_dates_iso_8601'}</h4>
    <div class="ipsMargin_top">
        <label>
            <input id="iso" type="text" value="{$dates['iso']}" data-input="iso">
        </label>
    </div>

    <h4>{lang='devtoys_dates_atom'}</h4>
    <div class="ipsMargin_top">
        <label>
            <input id="atom" type="text" value="{$dates['atom']}" data-input="atom">
        </label>
    </div>

    <h4>{lang='devtoys_dates_cookie'}</h4>
    <div class="ipsMargin_top">
        <label>
            <input id="cookie" type="text" value="{$dates['cookie']}" data-input="cookie">
        </label>
    </div>

    <h4>{lang='devtoys_dates_date_rfc'}</h4>
    <div class="ipsMargin_top">
        <label>
            <input id="rfc" type="text" value="{$dates['rfc']}" data-input="rfc">
        </label>
    </div>

    <h4>{lang='devtoys_dates_date_rfc3339'}</h4>
    <div class="ipsMargin_top">
        <label>
            <input id="rfc3339" type="text" value="{$dates['rfc3339']}" data-input="rfc3339">
        </label>
    </div>

    <h4>{lang='devtoys_dates_date_rfc3339e'}</h4>
    <div class="ipsMargin_top">
        <label>
            <input id="rfc3339e" type="text" value="{$dates['rfc3339e']}" data-input="rfc3339e">
        </label>
    </div>

    <h4>{lang='devtoys_dates_date_rfc7231'}</h4>
    <div class="ipsMargin_top">
        <label>
            <input id="rfc7231" type="text" value="{$dates['rfc7231']}" data-input="rfc7231">
        </label>
    </div>

    <h4>{lang='devtoys_dates_date_rss'}</h4>
    <div class="ipsMargin_top">
        <label>
            <input id="rss" type="text" value="{$dates['rss']}" data-input="rss">
        </label>
    </div>

    <h4>{lang='devtoys_dates_date_sql'}</h4>
    <div class="ipsMargin_top">
        <label>
            <input id="sql" type="text" value="{$dates['sql']}" data-input="sql">
        </label>
    </div>

    <h4>{lang='devtoys_dates_date_w3c'}</h4>
    <div class="ipsMargin_top">
        <label>
            <input id="w3c" type="text" value="{$dates['w3c']}" data-input="w3c">
        </label>
    </div>

    <div class="ipsMessage ipsMessage_info ipsMargin_top:half">
        {lang='devtoys_dates_utc_times'}
    </div>
</div>
