<ips:template parameters="" />

<div id="elDevToysDiffs" class="i-padding-top_0 i-padding_4" data-ipsstormdevtoysdiffs>
    <div class="ipsGrid ipsGrid--2">
        <div>
            <h4 class="ipsTitle ipsTitle--h4">{lang="storm_devtoys_diffs_source" sprintf="1"}</h4>
            <textarea id="source1" class="i-margin-top_2 ipsInput ipsInput--text ipsInput--wide ">Hello World!
foobar!</textarea>
                <ul class="ipsButtons ipsButtons--main i-margin-block_block">
                    <li>
                        <button class="ipsButton ipsButton--primary ipsButton--small" data-clear="#source1" title="{lang='storm_devtoys_clear'}">
                            <i class="fa fa-eraser"></i> {lang='storm_devtoys_clear'}
                        </button>
                    </li>
                </ul>
        </div>
        <div>
            <h4 class="ipsTitle ipsTitle--h4">{lang="storm_devtoys_diffs_source" sprintf="2"}</h4>
            <textarea id="source2" class="i-margin-top_2 ipsInput ipsInput--text ipsInput--wide ">Whatever World!
foobar!</textarea>
            <ul class="ipsButtons ipsButtons--main i-margin-block_block">
                <li>
                    <button class="ipsPos_right ipsButton ipsButton--primary ipsButton--small" data-clear="#source2" title="{lang='storm_devtoys_clear'}">
                        <i class="fa fa-eraser"></i> {lang='storm_devtoys_clear'}
                    </button>
                </li>
            </ul>
        </div>
    </div>
    <h4 class="ipsTitle ipsTitle--h4">{lang="storm_devtoys_diffs_diff"}</h4>
    <div id="diffs" class="i-margin-top_2"></div>
</div>
