<ips:template parameters="$decoded,$encoded" />

<div class="i-padding-top_0 i-padding_4" data-ipsstormdevtoyshtml>
    <h4 class="ipsTitle ipsTitle--h4">{lang='storm_devtoys_decoded'}</h4>
    <div class="i-margin-top_2">
        <textarea id="elDecodedContainer" class="ipsInput ipsInput--text ipsInput--wide">{$decoded|raw}</textarea>

        <ul class="ipsButtons ipsButtons--main i-margin-block_block">
            <li>
                <button class="ipsButton ipsButton--primary ipsButton--small" data-clear="elDecodedContainer">
                    <i class="fa fa-eraser"></i>  {lang='storm_devtoys_clear'}
                </button>
            </li>
            <li>
                <button class="ipsButton ipsButton--primary ipsButton--small" data-copy="elDecodedContainer" data-target-type="{lang='storm_devtoys_decoded'}">
                    <i class="fa fa-copy"></i>  {lang='storm_devtoys_copy'}
                </button>
            </li>
        </ul>
    </div>

    <h4 class="ipsTitle ipsTitle--h4">{lang='storm_devtoys_encoded'}</h4>

    <div class="i-margin-top_2">
        <textarea id="elEncodedContainer" class="ipsInput ipsInput--text ipsInput--wide">{$encoded|raw}</textarea>

        <ul class="ipsButtons ipsButtons--main i-margin-block_block">
            <li>
                <button class="ipsButton ipsButton--primary ipsButton--small" data-clear="elEncodedContainer">
                    <i class="fa fa-eraser"></i> {lang='storm_devtoys_clear'}
                </button>
            </li>
            <li>
                <button class="ipsButton ipsButton--primary ipsButton--small" data-copy="elEncodedContainer" data-target-type="{lang='storm_devtoys_encoded'}">
                    <i class="fa fa-copy"></i> {lang='storm_devtoys_copy'}
                </button>
            </li>
        </ul>
    </div>
</div>
