<ips:template parameters="$form" />

<div id="elDevToysDiffs" class="ipsPadding ipsClearfix" data-ipsdevtoysimages>
    <h2>{lang="devtoys_images_image"}</h2>
    {$form|raw}
    <button class="ipsButton ipsButton_primary ipsPos_right ipsMargin_bottom:half" data-convert>{lang="devtoys_images_convert"}</button>
    <div id="dl" class="ipsHide ipsType_center">
        <div>
            <a class="ipsButton ipsButton_primary ipsMargin_bottom:half">{lang="devtoys_images_download"}</a>
        </div>
        <img class="ipsImage ipsImage_thumb">
    </div>
</div>
