<ips:template parameters="$form,$lorem" />

<div class="i-padding-top_0 i-padding_4" data-ipsstormdevtoyslorem>
    {$form|raw}
        <ul class="ipsButtons ipsButtons--main i-margin-block_block">
            <li>
                <button class="ipsButton ipsButton--primary ipsButton--small" data-copy="elLoremContainer">
                    <i class="fa fa-copy"></i>
                    {lang='storm_devtoys_copy'}
                </button>
            </li>
            <li>
                <button class="ipsButton ipsButton--primary ipsButton--small" data-generate>{lang='storm_devtoys_lorem_generate'}
                </button>
            </li>
        </ul>
    <div class="i-margin-top_2" id="elLoremContainer">{$lorem|raw}</div>
</div>
