<ips:template parameters="$json,$pretty" />
<div class="i-padding-top_0 i-padding_4" data-ipsstormdevtoyspretty>
    <label for="elPrettyPrintJson">{lang="storm_devtoys_pretty_json"}</label>
    <textarea id="elPrettyPrintJson" class="ipsInput ipsInput--text ipsInput--wide ">{$json}</textarea>
    <ul class="ipsButtons ipsButtons--main i-margin-block_block">
        <li>
            <button class="ipsButton ipsButton--primary ipsButton--small" data-clear>
                <i class="fa fa-eraser"></i> {lang='storm_devtoys_clear'}</button>
        </li>
        <li>
            <button class="ipsButton ipsButton--primary ipsButton--small" data-pretty> {lang='storm_devtoys_pretty_make'}
            </button>
        </li>
    </ul>
    <div class="i-margin-top_2">
        <label for="elPrettyPrintPretty">{lang="storm_devtoys_pretty_pretty"}</label>
        <pre id="elPrettyPrintPretty">{$pretty|raw}</pre>
        <textarea id="elPrettyPrintPrettyCopy" class="ipsHide">{$pretty|raw}</textarea>
        <ul class="ipsButtons ipsButtons--main i-margin-block_block">
            <li>
                <button class="ipsButton ipsButton--primary ipsButton--small" data-copy="elPrettyPrintPretty">
                    <i class="fa fa-copy"></i>
                    {lang='storm_devtoys_copy'}
                </button>
            </li>
        </ul>
    </div>
</div>
