<ips:template parameters="$formCreate,$image,$path" />

<div id="elDevToysQR" class="ipsPadding ipsClearfix">
    <div class="devToysForms">
        <div class="ipsMargin_top ipsForm_horizontal">
            {$formCreate|raw}
            {{if $image !== null}}
            <div class="ipsType_center">
                <div>
                <a href="{url='app=devtoys&module=general&controller=toys&do=download&path={$path}&t=qr'}" class="ipsButton ipsButton_important">{lang="devtoys_images_download"}</a>
                </div>
                <img class="ipsImage ipsImage_thumb" src='{$image|raw}'>
            </div>
            {{endif}}
        </div>
    </div>
</div>
