<ips:template parameters="$form,$uuid" />

<div class="i-padding-top_0 i-padding_4" data-ipsstormdevtoysuuid>
    {$form|raw}

    <ul class="ipsButtons ipsButtons--main i-margin-block_block">
        <li>
            <button class="ipsButton ipsButton--primary ipsButton--small" id="clearuuid">
                <i class="fa fa-eraser"></i>{lang='storm_devtoys_clear'}
            </button>
        </li>
        <li>
            <button class="ipsButton ipsButton--primary ipsButton--small" id="generate">
                {lang="storm_devtoys_uuid_generator"}
            </button>
        </li>
    </ul>
    <div class="i-margin-top_2" id="elUuidContainer">
        {$uuid|raw}
    </div>
</div>
