<ips:template parameters="$menus, $apps, $plugins"/>
<ul id="stormDevBar" class="ipsList_inline ipsType_light ">
    {{if isset( $menus[0] ) }}
         {{foreach $menus[0] as $menu }}
            {{if $menu['ori'] == "plugins" or $menu['ori'] == "apps"}}
                {{if \IPS\IN_DEV }}
                    {{if $menu['ori'] == 'plugins' and $plugins }}
                        {template="li" group="dev" location="admin" app="storm" params="$menu, $menus, $plugins"}
                    {{endif}}
                    {{if $menu['ori'] == 'apps' and $apps }}
                        {template="li" group="dev" location="admin" app="storm" params="$menu, $menus, $apps"}
                    {{endif}}
                {{endif}}
            {{else}}
                {template="li" group="dev" location="admin" app="storm" params="$menu, $menus"}
            {{endif}}
        {{endforeach}}
    {{endif}}
 </ul>