<?php

/**
 * @brief       Member Singleton
 * @author      <a href='http://codingjungle.com'>Michael Edwards</a>
 * @copyright   (c) 2017 Michael Edwards
 * @package     IPS Social Suite
 * @subpackage  Storm
 * @since       -storm_since_version-
 * @version     3.0.4
 */

namespace IPS\storm\Pseudo;

if( !defined( '\IPS\SUITE_UNIQUE_KEY' ) )
{
    header( ( isset( $_SERVER[ 'SERVER_PROTOCOL' ] ) ? $_SERVER[ 'SERVER_PROTOCOL' ] :
            'HTTP/1.0' ) . ' 403 Forbidden' );
    exit;
}

class _Member
{
    protected $first = '';

    protected $last = '';

    protected $user = '';

    protected $email = '';

    protected $pass = '';

    protected $fontSize = 150;

    protected $baseSize = 250;

    protected $xOffset = 0;

    protected $yOffset = 0;

    protected $angle = 0;

    protected $shadowXOffset = 0;

    protected $shadowYOffset = 0;

    protected $font = '';

    static protected $availableClubIds = [];
    static protected $thereAreNoClubs = false;

    final public function __construct()
    {
        $this->first();
        $this->last();
        $this->username();
        $this->email();
        $fontFile = 'Roboto-Bold.ttf';
        $this->font = \IPS\ROOT_PATH . '/applications/storm/sources/Pseudo/' . $fontFile;
    }

    protected function first()
    {
        $rand = rand( 0, ( count( $this->firstNames ) - 1 ) );
        $this->first = $this->firstNames[ $rand ];
    }

    protected function last()
    {
        $rand = rand( 0, ( count( $this->lastNames ) - 1 ) );
        $this->last = $this->lastNames[ $rand ];
    }

    protected function username()
    {
        $rand = rand( 0, count( $this->userNames ) );
        $dividedBy = 3;
        $num = $rand / $dividedBy;
        if( is_int( $num ) )
        {
            $placeHolder = [ ".", "-", "_", " " ];
            $p = rand( 0, 3 );
            $placeHolder = $placeHolder[ $p ];
            $this->user = $this->first . $placeHolder . $this->last;
        }
        else
        {
            $rand = rand( 0, ( count( $this->userNames ) - 1 ) );
            $this->user = $this->userNames[ $rand ];
        }
    }

    protected function email()
    {
        $rand = rand( 0, ( count( $this->domains ) - 1 ) );
        $domain = $this->domains[ $rand ];
        $this->email = $this->user . "@" . $domain;
    }

    public function run( $password = null, $group = null, $avatar = null, $club = null )
    {
        $existing = \IPS\Member::load( $this->user, 'name' );

        if( !$existing->member_id )
        {

            if( !$group or !is_int( $group ) )
            {
                $group = \IPS\Settings::i()->getFromConfGlobal( 'member_group' );
            }

            if( $password )
            {
                $this->pass = sha1( rand( 1, 8800000083 ) );
            }
            else
            {
                $this->pass = $this->user;
            }

            $time = \IPS\storm\Pseudo\Generator::getTime();
            $member = new \IPS\Member;
            $member->name = $this->user;
            $member->member_group_id = $group;
            $member->email = $this->email;
            $member->joined = $time;
            $member->language = \IPS\Lang::defaultLanguage();
            $member->skin = 0;

            //put it into 3.x mode, it is much faster
            $member->members_pass_salt = mb_substr( $member->generateSalt(), 0, 8 );
            $member->members_pass_hash = $member->encryptedPassword( $this->pass );
            $member->members_bitoptions[ 'coppa_user' ] = false;
            $file = sha1( $this->user ) . ".png";
            $text = mb_substr( $this->user, 0, 1 );
            $text = mb_strtoupper( $text );

            if( $avatar )
            {
                $member->pp_main_photo = $this->generateAvatar( $file, $text, $this->user )->url;
                $member->pp_photo_type = "custom";
            }

            $member->save();

            /* Add member to club? */
            if ( $club )
            {
                if ( self::$thereAreNoClubs == false AND count( self::$availableClubIds ) == 0 )
                {
                    self::$availableClubIds = iterator_to_array( \IPS\Db::i()->select( 'id', 'core_clubs' ) );

                    if ( count( self::$availableClubIds ) == 0 )
                    {
                        self::$thereAreNoClubs = true;
                    }
                }

                if ( self::$thereAreNoClubs == false )
                {
                    $joinedAClub = false;

                    foreach( self::$availableClubIds as $club )
                    {
                        $areWeJoining = rand( 0, 1 ); /* 50% chance of joinging the club */

                        if ( $areWeJoining == 1 )
                        {
                            \IPS\Db::i()->insert( 'core_clubs_memberships', array(
                                'club_id'   => $club,
                                'member_id' => $member->member_id,
                                'joined'    => time(),
                                'status'    => 'member',
                                'added_by'  => NULL,
                                'invited_by'=> NULL,
                            ) );

                            $joinedAClub = true;
                        }
                    }

                    if ( $joinedAClub )
                    {
                        $member->rebuildPermissionArray();
                    }
                }
            }

            \IPS\storm\Generator::create( "members", $member->member_id );
        }
        else
        {
            $this->first();
            $this->last();
            $this->username();
            $this->email();
            $this->run( $password, $group, $avatar, $club );
        }
    }

    protected function generateAvatar( $file, $text, $full )
    {
        list( $r, $g, $b ) = $this->sscanf( $this->getColorForWords( $full ) );

        $font = $this->font;

        $fontSize = $this->fontSize;
        $imageSize = $this->baseSize;
        $angle = $this->angle;
        $alpha = 1;

        //have to do it this way, as sometimes # is here, other times its not
        $sha = "#" . str_replace( "#", '', mb_strtoupper( "000000" ) );
        list( $sr, $sg, $sb ) = $this->sscanf( $sha );
        //have to do it this way, as sometimes # is here, other times its not
        $fc = "#" . str_replace( "#", '', mb_strtoupper( "FFFFFF" ) );
        list( $fr, $fg, $fb ) = $this->sscanf( $fc );

        if( \IPS\Settings::i()->image_suite == 'imagemagick' and class_exists( 'Imagick', false ) )
        {
            if( $angle != 0 )
            {
                $angle = $angle * -1;
            }

            $x = $this->xOffset;
            $y = $this->yOffset;
            /* Create some objects */
            $image = new \Imagick();
            $draw = new \ImagickDraw();
            $string = "rgba({$r}, {$g}, {$b}, $alpha)";
            $shadow = "rgb({$sr},{$sg},{$sb})";
            $fontColor = "rgb({$fr},{$fg},{$fb})";
            $pixel = new \ImagickPixel( $string );

            /* New image */
            $image->newImage( $imageSize, $imageSize, $pixel );
            $image->setImageFormat( "png" );
            $draw = $draw;
            $image = $image;
            $draw->setTextAntialias( true );
            $draw->setGravity( \Imagick::GRAVITY_CENTER );
            $draw->setFont( $font );
            $draw->setFontSize( $fontSize );
            $draw->setFillColor( $shadow );
            $image->annotateImage( $draw, $x + $this->shadowXOffset, $y + $this->shadowYOffset, $angle, $text );
            /* white text */
            $draw->setFillColor( $fontColor );
            $draw->setFont( $font );
            $draw->setFontSize( $fontSize );
            $image->annotateImage( $draw, $x, $y, $angle, $text );
            $image->setImageFormat( 'png' );
            $file = \IPS\File::create( 'core_Profile', $file, $image );

        }
        else
        {
            $alpha = \floor( 127 * $alpha );
            $alpha = 127 - $alpha;

            list( $x, $y ) = $this->imageTTFCenter( $imageSize, $text, $font, $fontSize, $angle );
            $x = $x + $this->xOffset;
            $y = $y + $this->yOffset;
            $im = \imagecreatetruecolor( $imageSize, $imageSize );
            // background color, generated by
            $bg = \imagecolorallocatealpha( $im, $r, $g, $b, $alpha );
            \imagefill( $im, 0, 0, $bg );
            imagesavealpha( $im, true );
            //have to do it this way, as sometimes # is here, other times its not
            $shadow = \imagecolorallocate( $im, $sr, $sg, $sb );
            ImageTTFText( $im, $fontSize, $angle, $x + $this->shadowXOffset, $y + $this->shadowYOffset, $shadow, $font,
                $text );

            $fontColor = \imagecolorallocate( $im, $fr, $fg, $fb );
            ImageTTFText( $im, $fontSize, $angle, $x, $y, $fontColor, $font, $text );

            \ob_start();
            \imagepng( $im, null, 1, PNG_ALL_FILTERS );
            $fileContents = \ob_get_contents();
            $file = \IPS\File::create( 'core_Profile', $file, $fileContents );
            \ob_end_clean();
            \imagedestroy( $im );
        }

        return $file;
    }

    protected function sscanf( $data )
    {
        return \sscanf( $data, "#%02x%02x%02x" );
    }

    protected function getColorForWords( $str )
    {
        $str = strrev( $str );
        $code = dechex( crc32( $str ) );
        $code = mb_substr( $code, 0, 6 );

        return "#" . $code;
    }

    protected function imageTTFCenter( $image, $text, $font, $size, $angle )
    {
        // find the size of the text
        $box = \ImageTTFBBox( $size, $angle, $font, $text );

        $xr = abs( max( $box[ 2 ], $box[ 4 ] ) );
        $yr = abs( max( $box[ 5 ], $box[ 7 ] ) );

        // compute centering
        $x = intval( ( $image - $xr ) / 2 );
        $y = intval( ( $image + $yr ) / 2 );

        return [ $x, $y ];
    }


    protected $firstNames = [
        'Edris',
        'Eleonor',
        'Lana',
        'Gabrielle',
        'Kanesha',
        'Ryann',
        'Concetta',
        'Laurice',
        'Lewis',
        'Emmie',
        'Henry',
        'Avery',
        'Marya',
        'Lisa',
        'Nanci',
        'Norris',
        'Palma',
        'Jasper',
        'Bryan',
        'Marianela',
        'Antwan',
        'Myrtle',
        'Nereida',
        'Josefine',
        'Chris',
        'Vinnie',
        'Keeley',
        'Donald',
        'Denae',
        'Shane',
        'Erna',
        'Marilynn',
        'Ethelyn',
        'Sandy',
        'Vada',
        'Kenneth',
        'Odessa',
        'Jessica',
        'Ulysses',
        'Anneliese',
        'Gisela',
        'firstname',
        'Daniell',
        'Edie',
        'Mohammed',
        'Winter',
        'Malcom',
        'Dee',
        'Talisha',
        'Daryl',
        'Merideth',
        'Rayford',
        'Alleen',
        'Rodolfo',
        'Lucius',
        'Isis',
        'Yael',
        'Bonita',
        'Julietta',
        'Carmen',
        'Julie',
        'Katina',
        'Sidney',
        'Janene',
        'Ashley',
        'Elton',
        'Samara',
        'Suzann',
        'Marvel',
        'Julieta',
        'Francesco',
        'Cynthia',
        'Ed',
        'Shemeka',
        'Danuta',
        'Velia',
        'Andria',
        'Marcellus',
        'Buster',
        'Malvina',
        'Ned',
        'Dorothy',
        'Mohamed',
        'Dillon',
        'Shemika',
        'Michal',
        'Drema',
        'Darby',
        'Simona',
        'Juliette',
        'Terri',
        'Genevieve',
        'Jewell',
        'Peg',
        'Beckie',
        'Shelton',
        'Juliet',
        'Felisa',
        'Russell',
        'Bud',
        'Olga',
        'Mandie',
        'Adelia',
        'Larhonda',
        'Renee',
        'Caridad',
        'Jc',
        'Cherilyn',
        'Cecile',
        'Beatriz',
        'Avery',
        'Kellye',
        'Donna',
        'Angelyn',
        'Ronnie',
        'Janine',
        'Mikaela',
        'Liz',
        'Myrta',
        'Vergie',
        'Desirae',
        'Nathaniel',
        'Sammie',
        'Estella',
        'Roxanna',
        'Lacey',
        'Moises',
        'Nell',
        'Tamala',
        'Verda',
        'Inez',
        'Karoline',
        'Lien',
        'Nicolette',
        'Marie',
        'Latricia',
        'Alia',
        'Erline',
        'Tiffaney',
        'Frankie',
        'Omer',
        'Val',
        'Chana',
        'Raguel',
        'Conchita',
        'Joya',
        'Mafalda',
        'Minnie',
        'Tawna',
        'Miriam',
        'Sammie',
        'Magdalena',
        'Allegra',
        'Yaeko',
        'Nida',
        'Otha',
        'Rocky',
        'Angelia',
        'Demetria',
        'Cleora',
        'Renay',
        'Dortha',
        'Nerissa',
        'Aleida',
        'Regina',
        'Yvette',
        'Maxwell',
        'Jeni',
        'Billi',
        'Delmar',
        'Leila',
        'Alexander',
        'Yuriko',
        'Hilton',
        'Brady',
        'Arlena',
        'Sherice',
        'Deedee',
        'Avelina',
        'Eusebia',
        'Nguyet',
        'Miss',
        'Mimi',
        'Jen',
        'Alonso',
        'Lady',
        'Marlen',
        'Chante',
        'Daria',
        'Georgiann',
        'Priscilla',
        'Houston',
        'Ema',
        'Benedict',
        'Jayne',
        'Bianca',
        'Rena',
        'Barrie',
        'Earlie',
        'Mamie',
        'Gertha',
        'Cassidy',
        'Curt',
        'Shaun',
        'Yolando',
        'Elsie',
        'Ty',
        'Luise',
        'Talia',
        'Sharlene',
        'Edelmira',
        'Vernell',
        'Shena',
        'Hershel',
        'Jerrold',
        'Digna',
        'Dorine',
        'Felicitas',
        'Dalila',
        'Miranda',
        'Tuyet',
        'Felica',
        'Carlo',
        'Anika',
        'Natacha',
        'Carolin',
        'Yuri',
        'Cathryn',
        'Delphia',
        'Fannie',
        'Haydee',
        'Erminia',
        'Chastity',
        'Valeria',
        'Lilli',
        'Theresa',
        'Marsha',
        'Shonna',
        'Mertie',
        'Milo',
        'Collette',
        'Ofelia',
        'Fran',
        'Madison',
        'Lorriane',
        'Teresia',
        'Layne',
        'Refugio',
        'Ava',
        'Jetta',
        'Leola',
        'Vincenza',
        'Candie',
        'Edgardo',
        'Towanda',
        'Jae',
        'Clayton',
        'Kira',
        'Eloy',
        'Lurlene',
        'Carmela',
        'Quyen',
        'Kyle',
        'Xochitl',
        'Jason',
        'Nova',
        'Shari',
        'Nikia',
        'Jessie',
        'Karolyn',
        'Florentina',
        'Eugenio',
        'Roni',
        'Devon',
        'Sharyn',
        'Leslie',
        'Meaghan',
        'Karima',
        'Williams',
        'Nam',
        'Julio',
        'Eleanora',
        'Nathalie',
        'Edmundo',
        'Robbi',
        'Nakesha',
        'Cole',
        'Tomeka',
        'Latonya',
        'Shalon',
        'Young',
        'Selene',
        'Alice',
        'Eleanor',
        'Joanna',
        'Clelia',
        'Kindra',
        'Chauncey',
        'Kayce',
        'Yvone',
        'Clarissa',
        'Darci',
        'Mandy',
        'Leora',
        'Hildegard',
        'Wilbur',
        'Taylor',
        'Stephenie',
        'Cristina',
        'Sherrill',
        'Leighann',
        'Daniel',
        'Karyl',
        'Anglea',
        'Kiyoko',
        'Lavonia',
        'Jeannetta',
        'Ricardo',
        'Samual',
        'Herta',
        'Veronika',
        'Tyesha',
        'Jefferey',
        'Jack',
        'Minta',
        'Adella',
        'Sherill',
        'Rachele',
        'Dominica',
        'Joshua',
        'Kenny',
        'Dwain',
        'Horacio',
        'Shanita',
        'Chong',
        'Qiana',
        'Sonya',
        'Sanda',
        'Renata',
        'Maryjo',
        'Mercedez',
        'Scarlett',
        'Eboni',
        'Lois',
        'Stephine',
        'Dusty',
        'Maia',
        'Bertha',
        'Lavenia',
        'Kathyrn',
        'Ermelinda',
        'Terry',
        'Verdie',
        'Haley',
        'Katharyn',
        'Russell',
        'Glen',
        'Terresa',
        'Tinisha',
        'Diane',
        'Sammy',
        'Homer',
        'Emanuel',
        'Ethyl',
        'Merle',
        'Lawerence',
        'Lashawnda',
        'Ludie',
        'Deana',
        'Bethann',
        'Hiroko',
        'Kera',
        'Chance',
        'Josefa',
        'Eldridge',
        'Cecille',
        'Trena',
        'Marcene',
        'Tabetha',
        'Flora',
        'Peggie',
        'Claretha',
        'Louella',
        'Felisha',
        'Edgar',
        'Brande',
        'Rocio',
        'Chu',
        'Tanika',
        'Irish',
        'Adaline',
        'Kenyetta',
        'Audrea',
        'Candelaria',
        'Norberto',
        'Huey',
        'Kirsten',
        'Louis',
        'Marilu',
        'Taina',
        'Wayne',
        'Aja',
        'Octavia',
        'Eugene',
        'Matha',
        'Lane',
        'Melissia',
        'Jesus',
        'Kaci',
        'Ariane',
        'Elsa',
        'Celena',
        'Masako',
        'Elliot',
        'Otha',
        'Emmy',
        'Brett',
        'Cierra',
        'Bea',
        'Maida',
        'Colene',
        'Justina',
        'Prince',
        'Edna',
        'Mi',
        'Laurena',
        'Cortney',
        'Mariella',
        'Mai',
        'Jean',
        'Riva',
        'Jeri',
        'Bryanna',
        'Layla',
        'Omega',
        'Pauletta',
        'Thea',
        'Marcelle',
        'Keli',
        'Britt',
        'Wendolyn',
        'Loura',
        'Tony',
        'Wynell',
        'Jon',
        'Golda',
        'Paul',
        'Deon',
        'Laci',
        'Lajuana',
        'Anthony',
        'Cheryle',
        'Teena',
        'Lavette',
        'Flossie',
        'Eugena',
        'Kenton',
        'Scottie',
        'Ellie',
        'Claud',
        'Kamilah',
        'Reanna',
        'India',
        'Shakia',
        'Jazmine',
        'Johnetta',
        'Sueann',
        'Oralia',
        'Luigi',
        'Ryan',
        'Tory',
        'Laila',
        'Criselda',
        'Linnie',
        'Rina',
        'Racheal',
        'Leo',
        'Mara',
        'Jeanelle',
        'Bridgett',
        'Aimee',
        'Arnulfo',
        'Gerard',
        'Martin',
        'Brenna',
        'Matthew',
        'Elaina',
        'Eleanore',
        'Shawna',
        'Dewayne',
        'Thresa',
        'Rhonda',
        'Elvis',
        'Toby',
        'Isidra',
        'Keenan',
        'Eun',
        'Felecia',
        'Pinkie',
        'Dionna',
        'Cheri',
        'Leandra',
        'Hettie',
        'Elisa',
        'Emerita',
        'Chantel',
        'Elida',
        'Synthia',
        'Verline',
        'Lizbeth',
        'Buena',
        'Nichole',
        'Nicky',
        'Cindi',
        'Angel',
        'Vera',
        'Marin',
        'Latarsha',
        'Jamika',
        'Berna',
        'Dallas',
        'Kathey',
        'Doretha',
        'Jerrell',
        'Nilsa',
        'Frances',
        'Serita',
        'Leonarda',
        'Diann',
        'Fermin',
        'Daren',
        'Jeromy',
        'Marcela',
        'Shanda',
        'Jeffrey',
        'Halley',
        'Kenyatta',
        'Alfonso',
        'Dahlia',
        'Shea',
        'Kristeen',
        'Jody',
        'Lynna',
        'Cinderella',
        'Olimpia',
        'Kerri',
        'Hedy',
        'Brittni',
        'Kevin',
        'Hsiu',
        'Felicita',
        'Altagracia',
        'Zane',
        'Carylon',
        'Michiko',
        'Zofia',
        'Berneice',
        'Allen',
        'Amparo',
        'Reuben',
        'Emerson',
        'Shannon',
        'Zina',
        'Carla',
        'Nubia',
        'Gennie',
        'Ana',
        'Carrol',
        'Sylvie',
        'Esta',
        'Isabell',
        'Hector',
        'Magdalene',
        'Dorcas',
        'Yu',
        'Asuncion',
        'Deonna',
        'Lucien',
        'Clint',
        'Debera',
        'Lenard',
        'Winfred',
        'Leena',
        'Gordon',
        'Ingeborg',
        'Carletta',
        'Richard',
        'Casey',
        'Nana',
        'Damion',
        'Emelina',
        'Renea',
        'Seth',
        'Lorie',
        'Florene',
        'Fern',
        'Reynalda',
        'Zenia',
        'Rosario',
        'Carmina',
        'Nobuko',
        'Carey',
        'Lyn',
        'Paola',
        'Cherise',
        'Reda',
        'Fred',
        'Ruthanne',
        'Gwenda',
        'Melody',
        'Romana',
        'Cleveland',
        'Virgen',
        'Lauri',
        'Richie',
        'Pearly',
        'Latosha',
        'Freddie',
        'Aida',
        'Isabel',
        'Mahalia',
        'Kathy',
        'Randal',
        'Mechelle',
        'Neva',
        'Alane',
        'Ramona',
        'Earl',
        'Jarod',
        'Albertina',
        'Janetta',
        'Bennie',
        'Andera',
        'Florinda',
        'Darryl',
        'Eugene',
        'Conrad',
        'Magda',
        'Tomiko',
        'Larae',
        'Rosamaria',
        'Margherita',
        'Jerilyn',
        'Lidia',
        'Mose',
        'Delmy',
        'September',
        'Gayla',
        'Mercy',
        'Oliver',
        'Palmer',
        'Catheryn',
        'Celia',
        'Bong',
        'Arturo',
        'Miles',
        'Elli',
        'Eufemia',
        'Collene',
        'Rigoberto',
        'Neely',
        'Maurita',
        'Otelia',
        'Willia',
        'Trent',
        'Janina',
        'Janey',
        'Sacha',
        'Keren',
        'Tristan',
        'Suellen',
        'Lavone',
        'Nery',
        'Tommie',
        'Lucio',
        'Retta',
        'Patricia',
        'Dave',
        'Meridith',
        'Lena',
        'Margarite',
        'Adina',
        'Karin',
        'Serina',
        'Enriqueta',
        'Jada',
        'Belia',
        'Elliott',
        'Leisha',
        'Andrew',
        'Lizette',
        'Lorelei',
        'Daisy',
        'Lavera',
        'Sebrina',
        'Senaida',
        'Laraine',
        'Leonia',
        'Deandrea',
        'Clemencia',
        'Ester',
        'Laurence',
        'Claris',
        'Chandra',
        'Mitchel',
        'Freda',
        'Columbus',
        'Robby',
        'Kandace',
        'Tabatha',
        'Mica',
        'Woodrow',
        'Bernie',
        'Georgeanna',
        'Maybell',
        'Archie',
        'Mammie',
        'Gwenn',
        'Deloras',
        'Mary',
        'Reyes',
        'Jerome',
        'Lisbeth',
        'Nona',
        'Donita',
        'April',
        'Sallie',
        'Joetta',
        'Eva',
        'Elia',
        'Ida',
        'Dale',
        'Victor',
        'Nakita',
        'Gisele',
        'Hans',
        'Ariel',
        'Alan',
        'Stephani',
        'Sonny',
        'Naoma',
        'Fredia',
        'Tuan',
        'Refugia',
        'Jacqulyn',
        'Van',
        'Tod',
        'Marylee',
        'Margarett',
        'Sarita',
        'Tora',
        'Vickey',
        'Ying',
        'Will',
        'Melvin',
        'Orval',
        'Deanne',
        'Dianne',
        'Leo',
        'Johnnie',
        'Reva',
        'Mike',
        'Arcelia',
        'Monnie',
        'Anjelica',
        'Zelma',
        'Delila',
        'Laure',
        'Cleotilde',
        'Ashely',
        'Loreta',
        'Candida',
        'Emogene',
        'Bryon',
        'Dan',
        'Valrie',
        'Maryam',
        'Lonny',
        'Colton',
        'Randi',
        'Sherrie',
        'Evan',
        'Arlen',
        'Johnny',
        'Berry',
        'Minh',
        'Brinda',
        'Kiesha',
        'Carman',
        'Whitley',
        'Sharika',
        'Tiffani',
        'Jill',
        'Shenika',
        'Tova',
        'Sylvia',
        'Mirna',
        'Sung',
        'Hui',
        'Bobby'
    ];

    protected $lastNames = [
        'Nyhan',
        'Odriscoll',
        'Vardaro',
        'Fasciano',
        'Siverd',
        'Moyers',
        'Gunnoe',
        'Arguelles',
        'Pergram',
        'Hoppenrath',
        'Yates',
        'Kaps',
        'Siar',
        'Isabell',
        'Eatough',
        'Cowley',
        'Treharne',
        'Carlough',
        'Callais',
        'Kedzierski',
        'Marci',
        'Zamborsky',
        'Mctighe',
        'Melville',
        'Oberson',
        'Pontremoli',
        'Mee',
        'Kovack',
        'Wattson',
        'Tarnowski',
        'Longbottom',
        'Leuy',
        'Weant',
        'Clakley',
        'Hust',
        'Prevost',
        'Dundee',
        'Mccoulskey',
        'Womble',
        'Brodes',
        'Nygren',
        'Fetui',
        'Hinchee',
        'Place',
        'Caltagirone',
        'Girard',
        'Sampogna',
        'Nacci',
        'Bonifield',
        'Wedgeworth',
        'Bratek',
        'Waterhouse',
        'Shinabarger',
        'Basile',
        'Galashaw',
        'Creeks',
        'Lofaso',
        'Gushiken',
        'Olshefski',
        'Larkey',
        'Seabrooks',
        'Sabean',
        'Lanzillotti',
        'Koprowski',
        'Bollettino',
        'Mundt',
        'Peaker',
        'Donlan',
        'Baumeister',
        'Callihan',
        'Kleen',
        'Flaxman',
        'Osorno',
        'Limbo',
        'Sypniewski',
        'Grandon',
        'Reaume',
        'Revoir',
        'Schuetze',
        'Maish',
        'Derrick',
        'Birchall',
        'Sherwin',
        'Nygaro',
        'Swanteck',
        'Creselious',
        'Disorbo',
        'Pinder',
        'Skeels',
        'Cantoral',
        'Lorenc',
        'Janecka',
        'Rabner',
        'Remlinger',
        'Thenhaus',
        'Vaquez',
        'Bertha',
        'Mezquita',
        'Turnmyre',
        'Milliard',
        'Pyscher',
        'Preisler',
        'Kincheloe',
        'Ehli',
        'Latam',
        'Gremminger',
        'Montero',
        'Ehrenfeld',
        'Tsu',
        'Jolls',
        'Plamondon',
        'Geary',
        'Coiner',
        'Klobucar',
        'Tsemetzis',
        'Fees',
        'Harvilicz',
        'Luangsingotha',
        'Scheppe',
        'Truchon',
        'Furey',
        'Hokama',
        'Bechtol',
        'Redick',
        'Cisneroz',
        'Marshalek',
        'Plassmeyer',
        'Blausey',
        'Whitherspoon',
        'Woodmancy',
        'Atchley',
        'Ptomey',
        'Kringel',
        'Be',
        'Cuthill',
        'Penird',
        'Cavers',
        'Mongillo',
        'Lainson',
        'Alexanders',
        'Cherubin',
        'Doegg',
        'Nihart',
        'Luskey',
        'Scrim',
        'Kitzmiller',
        'Peper',
        'Hald',
        'Gagarin',
        'Mcginnity',
        'Lauer',
        'Spurr',
        'Salters',
        'Pears',
        'Puhuyaoma',
        'Singh',
        'Flister',
        'Donnick',
        'Searls',
        'Ketzler',
        'Demien',
        'Vandersteen',
        'Brzezowski',
        'Nesler',
        'Majercik',
        'Litscher',
        'Stefford',
        'Sluski',
        'Vita',
        'Wichert',
        'Vandeveble',
        'Vonderahe',
        'Bazan',
        'Vanderroest',
        'Gislason',
        'Bottorff',
        'Jolivette',
        'Evanchalk',
        'Mcelhannon',
        'Pellot',
        'Jegede',
        'Thrope',
        'Kicker',
        'Anania',
        'Tashjian',
        'Coggin',
        'Pageau',
        'Reese',
        'Jurney',
        'Calley',
        'Kurzyniec',
        'Filice',
        'Hendler',
        'Stanifer',
        'Witcraft',
        'Mcclarty',
        'Eagleston',
        'Lincoln',
        'Boyar',
        'Daleo',
        'Zeals',
        'Weidower',
        'Ainslie',
        'Legler',
        'Vancamp',
        'Haraldson',
        'Biscari',
        'Kietzman',
        'Higgs',
        'Kassing',
        'Dousay',
        'Pelliccia',
        'Chicoine',
        'Luzania',
        'Anwar',
        'Emperor',
        'Yanity',
        'Toban',
        'Phaneuf',
        'Lantzy',
        'Gari',
        'Garced',
        'Salsbury',
        'Botkins',
        'Naranjo',
        'Kurter',
        'Briceno',
        'Canto',
        'Elms',
        'Vicars',
        'Duchon',
        'Dixion',
        'Nussbaum',
        'Mckeithen',
        'Prus',
        'Glee',
        'Wilmoth',
        'Febbo',
        'Korner',
        'Studler',
        'Blazek',
        'Merine',
        'Wayt',
        'Finey',
        'Lepke',
        'Joss',
        'Barbosa',
        'Dornbos',
        'Ricotta',
        'Geelan',
        'Murzyn',
        'Steenberg',
        'Gampong',
        'Krepp',
        'Yamaguchi',
        'Wimbrow',
        'Rougier',
        'Wolnik',
        'Mapa',
        'Brafman',
        'Marten',
        'Foutch',
        'Hielscher',
        'Olazabal',
        'Saling',
        'Alsbrook',
        'Miramontez',
        'Jantz',
        'Goeckel',
        'Poitier',
        'Jahnsen',
        'Mahurin',
        'Gionest',
        'Grabe',
        'Conklin',
        'Hespen',
        'Pendergraph',
        'Ojeda',
        'Siewers',
        'Gammell',
        'Closson',
        'Booth',
        'Chasnoff',
        'Hemberger',
        'Giancola',
        'Ketter',
        'Homes',
        'Meador',
        'Tyus',
        'Deshon',
        'Bookhardt',
        'Cardon',
        'Kirklen',
        'Dulak',
        'Rivett',
        'Elbaum',
        'Flanigan',
        'Frischman',
        'Covarrubias',
        'Witucki',
        'Slape',
        'Kalin',
        'Lovin',
        'Sioma',
        'Drown',
        'Ikehara',
        'Kupetz',
        'Degler',
        'Diggins',
        'Walrod',
        'Quezaire',
        'Assis',
        'Stas',
        'Stubbendeck',
        'Basford',
        'Dobiesz',
        'Thady',
        'Bocci',
        'Shapskinsky',
        'Fegurgur',
        'Botz',
        'Tacason',
        'Couvillier',
        'Nasseri',
        'Castells',
        'Arjune',
        'Tewani',
        'Geney',
        'Fata',
        'Rusnak',
        'Senst',
        'Babineau',
        'Bettle',
        'Debruce',
        'Roblin',
        'Louka',
        'Hepperly',
        'Eversole',
        'Decoursey',
        'Mczeal',
        'Bayley',
        'Pavlovich',
        'Beston',
        'Pilkins',
        'Brox',
        'Tachauer',
        'Angustia',
        'Kolinsky',
        'Brazzell',
        'Arribas',
        'Bath',
        'Sovey',
        'Agreda',
        'Trembly',
        'Breitenbucher',
        'Hujer',
        'Kant',
        'Ultseh',
        'Norstrud',
        'Schildknecht',
        'Avance',
        'Kanemoto',
        'Smedley',
        'Sadusky',
        'Borodec',
        'Maarx',
        'Slicker',
        'Smid',
        'Dettmann',
        'Milliren',
        'Dubach',
        'Mcwhinney',
        'Szuba',
        'Allgier',
        'Bridgers',
        'Wauson',
        'Freimuth',
        'Miyoshi',
        'Lunch',
        'Adamek',
        'Giardino',
        'Likos',
        'Fragosa',
        'Gomoll',
        'Houlahan',
        'Malmgren',
        'Bukhari',
        'Kennel',
        'Kaplin',
        'Mcdunn',
        'Stpierrie',
        'Pozniak',
        'Bedson',
        'Maceachern',
        'Warschaw',
        'Delbo',
        'Melo',
        'Yandle',
        'Hail',
        'Romo',
        'Richison',
        'Mesidor',
        'Simonetta',
        'Flentroy',
        'Winnike',
        'Grega',
        'Steinhardt',
        'Vaccarello',
        'Chesick',
        'Widney',
        'Murrow',
        'Heldt',
        'Mcglothern',
        'Poisson',
        'Weese',
        'Rusboldt',
        'Hyle',
        'Curz',
        'Kniceley',
        'Coppa',
        'Rupel',
        'Hicken',
        'Browner',
        'Toodle',
        'Milinazzo',
        'Hongach',
        'Filippini',
        'Czaplinski',
        'Vuillemot',
        'Hargett',
        'Vanhulle',
        'Kemme',
        'Manne',
        'Richarson',
        'Rifai',
        'Brenna',
        'Penez',
        'Crutchfield',
        'Shindler',
        'Mutana',
        'Reisling',
        'Escudero',
        'Telleria',
        'Alhaddad',
        'Lillie',
        'Eleazer',
        'Hwang',
        'Simokat',
        'Rutski',
        'Harless',
        'Parzych',
        'Anastasia',
        'Emiliano',
        'Bookamer',
        'Rockwell',
        'Pellon',
        'Brymer',
        'Foxhoven',
        'Yambo',
        'Miquel',
        'Shaff',
        'Huguley',
        'Eklund',
        'Little',
        'Cupp',
        'Stromberg',
        'Toline',
        'Dibrell',
        'Lickey',
        'Vissering',
        'Fornili',
        'Spille',
        'Barker',
        'Schwenk',
        'Volesky',
        'Almaras',
        'Mahrer',
        'Bashinelli',
        'Linsay',
        'Ragain',
        'Trudell',
        'Uchytil',
        'Arquette',
        'Yanagihara',
        'Albelo',
        'Cockburn',
        'Schnieders',
        'Dudman',
        'Jaskot',
        'Hiley',
        'Falso',
        'Kamrath',
        'Buell',
        'Brandeis',
        'Fadness',
        'Rauchwerger',
        'Lockridge',
        'Harian',
        'Metropoulos',
        'Billiott',
        'Maenner',
        'Rodriguel',
        'Whisenton',
        'Custeau',
        'Bakes',
        'Loughary',
        'Crabbs',
        'Picariello',
        'Benjamine',
        'Goatley',
        'Ennenga',
        'Bressi',
        'Clouthier',
        'Zuehlsdorff',
        'Blackard',
        'Kaczmarek',
        'Demorizi',
        'Agnew',
        'Acker',
        'Vixayack',
        'Reischl',
        'Surette',
        'Shepler',
        'Liew',
        'Nest',
        'Lefort',
        'Keup',
        'Tippery',
        'Mayorga',
        'Scale',
        'Colpi',
        'Caroli',
        'Pewitt',
        'Mazzariello',
        'Rokicki',
        'Brester',
        'Beiter',
        'Maenius',
        'Trattner',
        'Niermann',
        'Osterholt',
        'Hartup',
        'Magallanes',
        'Patel',
        'Ginkel',
        'Misasi',
        'Schoffstall',
        'Kollasch',
        'Jecklin',
        'Winstead',
        'Hoage',
        'Stachura',
        'Clint',
        'Clancey',
        'Launderville',
        'Leyson',
        'Mussell',
        'Mckeel',
        'Domingue',
        'Valenciana',
        'Buelna',
        'Liberto',
        'Corrigeux',
        'Pompi',
        'Minon',
        'Pesce',
        'Parenteau',
        'Fredline',
        'Whatley',
        'Kostiuk',
        'Witherow',
        'Libberton',
        'Monforte',
        'Rattler',
        'Turvaville',
        'Furl',
        'Sitterson',
        'Summerfield',
        'Masso',
        'Gallivan',
        'Buena',
        'Stalls',
        'Brevig',
        'Whitbread',
        'Prochaska',
        'Gannaway',
        'Pacior',
        'Farry',
        'Bernhard',
        'Woodrich',
        'Cogliano',
        'Rhodehamel',
        'Mandella',
        'Tambe',
        'Heitger',
        'Reidenbach',
        'Mcelroy',
        'Salsedo',
        'Fontaine',
        'Bomia',
        'Cedeno',
        'Water',
        'Stakemann',
        'Vanschuyver',
        'Dubovsky',
        'Onorata',
        'Glish',
        'Lizardi',
        'Coufal',
        'Rottner',
        'Hutchinson',
        'Pomella',
        'Merrills',
        'Wieloch',
        'Dunnington',
        'Mcnolty',
        'Gerland',
        'Breeden',
        'Dobrich',
        'Finton',
        'Morning',
        'Liedy',
        'Liggett',
        'Garlett',
        'Sanmartin',
        'Vanella',
        'Prial',
        'Bradner',
        'Baird',
        'Stweart',
        'Clure',
        'Tith',
        'Dechick',
        'Witthoft',
        'Lowing',
        'Gossling',
        'Moehlman',
        'Venske',
        'Paker',
        'Trupp',
        'Kindall',
        'Mungo',
        'Schadegg',
        'Fearon',
        'Wisse',
        'Hennies',
        'Harby',
        'Syrett',
        'Windam',
        'Carrao',
        'Weflen',
        'Rieken',
        'Grastorf',
        'Hillard',
        'Bourgon',
        'Wicinsky',
        'Litvak',
        'Cremeens',
        'Lubinski',
        'Auzat',
        'Soder',
        'Ivie',
        'Bergener',
        'Foreman',
        'Perdew',
        'Meusa',
        'Trupiano',
        'Adduci',
        'Rombs',
        'Marinkovic',
        'Lundell',
        'Chiariello',
        'Mastropietro',
        'Kataoka',
        'Benston',
        'Sneeden',
        'Varos',
        'Wachal',
        'Eidem',
        'Mezza',
        'Holzner',
        'Vanelderen',
        'Lalley',
        'Farria',
        'Greeb',
        'Pasvizaca',
        'Regel',
        'Goliday',
        'Gravito',
        'Coriaty',
        'Wallenstein',
        'Hobel',
        'Snellgrove',
        'Koria',
        'Kopsho',
        'Ledue',
        'Smigel',
        'Mondejar',
        'Tarring',
        'Gomer',
        'Muellner',
        'Himelstein',
        'Frilling',
        'Piskel',
        'Ditzel',
        'Shaline',
        'Dilella',
        'Czolba',
        'Colombe',
        'Morisky',
        'Scherz',
        'Sterlin',
        'Mcclanan',
        'Wojdak',
        'Gilomen',
        'Elawar',
        'Gumbert',
        'Murrillo',
        'Keoghan',
        'Mcglathery',
        'Spaman',
        'Arrojo',
        'Caballes',
        'Matalka',
        'Ronson',
        'Habeck',
        'Respass',
        'Merna',
        'Ouimette',
        'Tinelli',
        'Beckendorf',
        'Quade',
        'Mottershead',
        'Hollender',
        'Virani',
        'Sevey',
        'Mimnaugh',
        'Strauch',
        'Langwith',
        'Pellom',
        'Malpica',
        'Lindall',
        'Chanchuan',
        'Thibodeau',
        'Brohn',
        'Serrao',
        'Friedrichs',
        'Purcell',
        'Loske',
        'Monsanto',
        'Marecki',
        'Mcgannon',
        'Belasco',
        'Willaby',
        'Blazich',
        'Willier',
        'Citrone',
        'Carrizales',
        'Nahrstedt',
        'Lukas',
        'Gulston',
        'Villanueva',
        'Leyvas',
        'Offutt',
        'Podaras',
        'Aarons',
        'Meryman',
        'Favila',
        'Dardon',
        'Hantzarides',
        'Krauskopf',
        'Meinders',
        'Schlereth',
        'Hullum',
        'Divenere',
        'Cattrell',
        'Boor',
        'Mckusick',
        'Swartz',
        'Goldenman',
        'Anderman',
        'Arrants',
        'Massaglia',
        'Tippets',
        'Opperman',
        'Marbury',
        'Grzyb',
        'Delong',
        'Secord',
        'Faro',
        'Montminy',
        'Hermus',
        'Goudie',
        'Evinger',
        'Macha',
        'Pigao',
        'Vauters',
        'Etter',
        'Shroll',
        'Atamian'
    ];

    protected $userNames = [
        'Playboyize',
        'Gigastrength',
        'Deadlyinx',
        'Techpill',
        'Methshot',
        'Methnerd',
        'TreeEater',
        'PackManBrainlure',
        'Carnalpleasure',
        'Sharpcharm',
        'Snarelure',
        'Skullbone',
        'Burnblaze',
        'Emberburn',
        'Emberfire',
        'Evilember',
        'Firespawn',
        'Flameblow',
        'SniperGod',
        'TalkBomber',
        'SniperWish',
        'RavySnake',
        'WebTool',
        'TurtleCat',
        'BlogWobbles',
        'LuckyDusty',
        'RumChicken',
        'StonedTime',
        'CouchChiller',
        'VisualMaster',
        'DeathDog',
        'ZeroReborn',
        'TechHater',
        'eGremlin',
        'BinaryMan',
        'AwesomeTucker',
        'FastChef',
        'JunkTop',
        'PurpleCharger',
        'CodeBuns',
        'BunnyJinx',
        'GoogleCat',
        'StrangeWizard',
        'Fuzzy_Logic',
        'New_Cliche',
        'Ignoramus',
        'Stupidasole',
        'whereismyname',
        'Nojokur',
        'Illusionz',
        'Spazyfool',
        'Supergrass',
        'Dreamworx',
        'Fried_Sushi',
        'Stark_Naked',
        'Need_TLC',
        'Raving_Cute',
        'Nude_Bikergirl',
        'Lunatick',
        'Garbage Can Lid',
        'Crazy_Nice',
        'Booteefool',
        'Harmless_Venom',
        'Lord_Tryzalot',
        'Sir_Gallonhead',
        'Boy_vs_Girl',
        'MPmaster',
        'King_Martha',
        'Spamalot',
        'Soft_member',
        'girlDog',
        'Evil_kitten',
        'farquit',
        'viagrandad',
        'happy_sad',
        'haveahappyday',
        'SomethingNew',
        '5mileys',
        'cum2soon',
        'takes2long',
        'w8t4u',
        'askme',
        'Bidwell',
        'massdebater',
        'iluvmen',
        'Inmate',
        'idontknow',
        'likme',
        'lostmypassword',
        'kizzmybutt',
        'hairygrape',
        'Poker_Star',
        '362bmx',
        'p0pps',
        'wtfson234',
        'MrEpicComedy',
        'njprince0225',
        'hasdgf',
        'urujuanma',
        'xFryzeNxCoDx',
        'IcanHybrid',
        'mrdefenitive',
        'EminemRemembered',
        '123monkey25',
        'xZestaa',
        'RbkStatsz',
        'whateverwhatever44',
        'iAMnotAwaffle',
        'chavidgb',
        'Wartijn',
        'CaseyCran1',
        'divinegale',
        'teamULTiMaTeMW2',
        'theproselytebros',
        'mrbobb1',
        'linusekepek',
        '999moparscape999',
        'TheRunescapeExploit',
        'JOJIMDIE',
        'amer361',
        'RunescapeTopClips',
        'charlie3ize',
        'ColdBlood2h',
        'ROFLCOPTT3R',
        'pheinex1',
        'san1122',
        'anjo229',
        'youri842',
        'ethan2390',
        '16lauti16',
        'broodoos',
        'OnlineFromLithuania',
        'DarkKnight2521',
        'hphh525',
        'rsmaster2k9',
        'morrifield',
        'ImThePlug',
        'heshe377',
        'CodMoDDz',
        'EliteDrogo',
        'lethal172',
        'omghatkid',
        'xCrucialSoulx',
        'Zougwarr',
        'ThatGuyWhoPlaysRS',
        'born4ko',
        'thebball10fosho',
        'jodyenty123',
        'sk1lls2dead',
        'MrCesarbeast',
        'nfsmwbefast',
        'YourIdeaa',
        'TheINTERVENTIONx',
        'evilkittens9',
        'MrGroupkiller',
        'XxL0SANG3L0SxX',
        'devinpkk',
        'jellyjoe3',
        'loumanlou2',
        'loveofmith',
        'NatureInside',
        'TugasempireChannel',
        'dumemonkey96',
        'tom1994ftw',
        'ThirdAgeFilm',
        'BlonDiiHD',
        'xXDreadDemonXx',
        'kingbling0001',
        'sasukestar4',
        'newtechalex',
        'omagiickzz',
        'WtfStarAsh',
        'Imbbqcombatarms',
        'misterniek',
        'xzzachzx',
        'lunarrune65',
        'joshmanownz',
        'alvin99ful',
        'Meomixftwyo',
        'TheRsfinest',
        'Little0aks',
        'vadetuhoo',
        'XrushzealX',
        'hesamonster',
        'w0zz0r',
        'bijaycarlosrana',
        'madux60',
        'LickitungSushi',
        'keeprockloud',
        'derejagulation',
        'runescapetryhard',
        'somebodyruleE',
        'xxsickh3dxx',
        'tastyturnips1',
        'mandomofights',
        'Eddyfromhell',
        'amazingnambitious',
        'oOShahaOo',
        'pksoogood',
        'V0llume',
        'inferno3232',
        'stormhunter77',
        'waggle72',
        '48hour1',
        'katoporro',
        'ftwherman',
        'irepmerked',
        'm40wn3r',
        'Golddust21',
        'mrandyrulz',
        'dellfell4',
        'nightperson11',
        'xxubesinxx',
        'mrdogfat',
        'chaosjobe332',
        'HighxFinity',
        'Noxiousxx',
        'FinalProCut',
        'LmfaoTreeby',
        'rsalien',
        'alexisrsacc1',
        'chilly291',
        'iiJubio',
        'alld4wypur',
        'benhughes2k7',
        'OBBYMAULEDvids',
        'megawownice',
        'NotShivShank',
        'kilerius1',
        'vindicta911',
        'qpidschkhold',
        'AtomicRs',
        'NEONGT1',
        'TheDivine770',
        'crackkorn814',
        'MotionsRS',
        'rsBlankNames',
        'Jzing29',
        '123shuffle123',
        'imgnastyi',
        'iCantSleepi',
        'TimeTutorials',
        'taylormade851',
        'overbeckjagex',
        'zztopzz1995',
        'ruster1971',
        'ownageRSproduction',
        'Cavent50',
        'pacifier1995',
        'TheGoldenSmoke',
        'MayhemMaker1500',
        '33the',
        'renas97',
        'myfisturscars',
        'dude2die4',
        'thebenneato',
        'killerberdo',
        'TakeDown427',
        'EraserGaming',
        'mattyh099',
        'ownt3',
        '90Ninerss',
        'Jtstudi0s',
        'iiTaKeOvA',
        'fi0reskater',
        'trucker1278',
        'Ashibo1',
        'PanicSAFE',
        'unholyfaith1',
        'maximedn',
        'ikill99ers',
        'bubblesthatkid',
        'anchainbody',
        'superrstools',
        'cravendale',
        'FlyGuyD10',
        'ChaoticLegend1',
        'quagmya',
        'kpobrien95',
        'GodWillAnswerAll',
        'Maniack017',
        'JusqRS',
        'r4pidzzz',
        'H3FBUNDY',
        'RuneScaoeComments',
        'omega18800881',
        'kech4',
        'adzii1',
        'oversholder',
        'benntheone7',
        'bustuhnuut',
        'Coocooso',
        'nooby0wner',
        'wholsamber',
        'FuZioNzProoF',
        'yanifanfan20',
        'Y0GGlE',
        'rde1596',
        'EyEamRUtardud',
        'errorvidz',
        'coolguywithashirt',
        'slbcampeao1',
        'kamikazemomma5',
        'ToontownRoxGuy',
        'Failgex',
        'pkk1n95ftw',
        'kevytpete1',
        'darkrigh3',
        'varkentje79',
        'darkrigh3',
        'chite02',
        'treasuretrails',
        'CodCats',
        'tmanwee',
        'vlogginngrunescape',
        '1991ChelseaFC',
        'iKodeeezy',
        'JeWeetZelf151',
        'MiDgEtMaFiA123',
        'B12Badboy',
        'oldhag149',
        'leothycles',
        'danthelegendman',
        'pleasureu4gold',
        'fruktHD',
        'xslayinggawdx',
        'team3d180',
        'postbusxftw',
        'eddyfromhell',
        'OhEmGee91',
        'MyRikker',
        '30blah30',
        'polobilenmin',
        'Wapashaify',
        'taix250',
        'BiscuitRisk',
        'artemissf125',
        'timwood70',
        'poopymonster100',
        'peoria007',
        'sword199723',
        'theairsoftstuff4u',
        'Down2Skills',
        'PeytonManningguy',
        'bindunitlures',
        'pkproductt',
        'Dingdingdongish',
        'igorts10',
        'INUyAsUa',
        'mrmilzor',
        'pk2hell',
        'cmepwnurmom',
        'MrBuster265',
        'rsnamedilsta123',
        'MrTiagoRicci',
        'ox0powned0xo',
        'Dylanman187',
        'porkypine1888',
        'articsnelscope',
        'iamTHEbombar30',
        'maxxedone',
        '1337Joeman',
        'RsGuidesIK',
        'spudyman2'
    ];

    protected $domains = [
        'aol.com',
        'att.net',
        'comcast.net',
        'facebook.com',
        'gmail.com',
        'gmx.com',
        'googlemail.com',
        'google.com',
        'hotmail.com',
        'hotmail.co.uk',
        'mac.com',
        'me.com',
        'mail.com',
        'msn.com',
        'live.com',
        'sbcglobal.net',
        'verizon.net',
        'yahoo.com',
        'yahoo.co.uk',
        'email.com',
        'games.com',
        'gmx.net',
        'hush.com',
        'hushmail.com',
        'icloud.com',
        'inbox.com',
        'lavabit.com',
        'love.com',
        'outlook.com',
        'pobox.com',
        'rocketmail.com',
        'safe-mail.net',
        'wow.com',
        'ygm.com',
        'ymail.com',
        'zoho.com',
        'fastmail.fm',
        'yandex.com',
        'bellsouth.net',
        'charter.net',
        'comcast.net',
        'cox.net',
        'earthlink.net',
        'juno.com',
        'btinternet.com',
        'virginmedia.com',
        'blueyonder.co.uk',
        'freeserve.co.uk',
        'live.co.uk',
        'ntlworld.com',
        'o2.co.uk',
        'orange.net',
        'sky.com',
        'talktalk.co.uk',
        'tiscali.co.uk',
        'sina.com',
        'qq.com',
        'naver.com',
        'hanmail.net',
        'daum.net',
        'nate.com',
        'yahoo.co.jp',
        'yahoo.co.kr',
        'yahoo.co.id',
        'yahoo.co.in',
        'yahoo.com.sg',
        'yahoo.com.ph',
        'hotmail.fr',
        'live.fr',
        'laposte.net',
        'yahoo.fr',
        'wanadoo.fr',
        'orange.fr',
        'gmx.fr',
        'sfr.fr',
        'neuf.fr',
        'free.fr',
        'gmx.de',
        'hotmail.de',
        'live.de',
        'online.de',
        't-online.de',
        'web.de',
        'yahoo.de',
        'mail.ru',
        'rambler.ru',
        'yandex.ru',
        'ya.ru',
        'list.ru',
        'hotmail.be',
        'live.be',
        'skynet.be',
        'voo.be',
        'tvcablenet.be',
        'telenet.be',
        'hotmail.com.ar',
        'live.com.ar',
        'yahoo.com.ar',
        'fibertel.com.ar',
        'speedy.com.ar',
        'arnet.com.ar',
        'hotmail.com',
        'gmail.com',
        'yahoo.com.mx',
        'live.com.mx',
        'yahoo.com',
        'hotmail.es',
        'live.com',
        'hotmail.com.mx',
        'prodigy.net.mx',
        'msn.com',
        'yahoo.com.br',
        'hotmail.com.br',
        'outlook.com.br',
        'uol.com.br',
        'bol.com.br',
        'terra.com.br',
        'ig.com.br',
        'itelefonica.com.br',
        'r7.com',
        'zipmail.com.br',
        'globo.com',
        'globomail.com',
        'oi.com.br'
    ];
}