<ips:template parameters="int $phpStorm" />
<div class="stormProfilerProxyBox" data-ipsstormprofilerproxy>
    <ul class="ipsForm ipsForm--default ipsForm--template">
        <li class="p-4">
            <input type="checkbox" id="elStorm_proxy_write_mixin" name="storm_proxy_write_mixin" value="1" checked>
            <label for="elStorm_proxy_write_mixin" id="elStorm_proxy_write_mixin_label" data-role="label">
                Write in @mixin for Owned Models
            </label>
        </li>
        <li class="p-4">
            <input type="checkbox" id="elStorm_proxy_other_models" name="storm_proxy_other_models" value="1" checked>
            <label for="elStorm_proxy_other_models" id="elStorm_proxy_other_models_label" data-role="label">
                Create Proxies for non-owned models
            </label>
        </li>
        <li class="ipsSubmitRow">
            <button type="button" class="ipsButton ipsButton--primary" tabindex="2" accesskey="s" data-phpstorm="{$phpStorm}" data-start>
                Start
            </button>
        </li>
    </ul>
</div>